name: Simple Test Runner Cypress CI/CD
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0

      - name: Install Dependencies
        run: npm install

      - name: Cypress.io
        uses: cypress-io/github-action@v5.5.1
        with:
          browser: chrome

      - name: Upload Cypress Test Results
        if: always() # ensures the artifacts are uploaded even if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results # adjust this path based on where Cypress stores your test results

